# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Zhe Liu # Website name

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 刘哲
  params:
    description: 刘哲个人网站
  menu:
    main:
      - name: 个人简介
        url: '#about'
        weight: 10
      - name: 兴趣爱好
        url: '#skills'
        weight: 20
      - name: 教育背景
        url: '#experience'
        weight: 30
      - name: 项目经历
        url: '#posts'
        weight: 40
      - name: 文章发表
        url: '#posts'
        weight: 50
      - name: 联系方式
        url: '#contact'
        weight: 60
