# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  title: Zhe Liu # Website name

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: 刘哲
  params:
    description: 刘哲个人网站
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Skills
        url: '#skills'
        weight: 20
      - name: Education
        url: '#experience'
        weight: 30
      - name: Engineering Projects
        url: '#posts'
        weight: 40
      - name: Contact
        url: '#contact'
        weight: 50
